### PR TITLE
New GitHub Action - Check Broken Links

### LINKED ISSUE #354: Broken Link Checker - Github Action
I believe that it will be a great idea to setup a GitHub action that runs periodically and checks for broken links.
 It will check all repository links once per day and create an issue in case of errors.

Github action to check for broken links in Markdown, HTML, and text files using [Lychee](https://lychee.cli.rs/), a fast link checker written in Rust.

Here is a full example of a GitHub workflow file:

It will check all repository links once per day and create an issue in case of errors.

```yaml
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```

I'd like to share my experience with [Lychee](https://lychee.cli.rs/). I came across it yesterday and integrated it into my project. While it was helpful in identifying some broken links, it also generated some false positives (links that appear broken but function correctly). I'm still exploring the tool's functionality to potentially fine-tune its accuracy.

On a separate note, I encountered a permissions issue when trying to open new issues.

Project implementations:

- [documentation.breadnet.co.uk](https://github.com/userbradley/documentation.breadnet.co.uk) ---> [GitHub action](https://github.com/userbradley/documentation.breadnet.co.uk/actions/runs/9006655904)
- [freeForGeeks](https://github.com/JuanPabloDiaz/freeForGeeks) ---> [GitHub action](https://github.com/JuanPabloDiaz/freeForGeeks/actions/runs/9009525313)

here is an example from my own project:
image

I hope this helps

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
This workflow is designed to automatically check for broken links in Markdown files within the repository. It runs under several conditions: 1. on pull requests to the 'main' branch, 2. on manual triggers, and 3. on a scheduled basis. If any broken links are found, the workflow creates or updates a GitHub issue with the details.

The Link Checker step reads the `.lycheeignore` file specified by the --exclude-file .lycheeignore argument to determine which links or files should be excluded from the link checking process.

Fixes #354

## Main Changes

- Add Workflow
- Add ignore file
- Add false positive URLs to ignore file
- Fix URL in readme
- Delete broken links in readme
- run tests

-   [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/marcelscruz/public-apis/blob/main/CONTRIBUTING.md)
-   [ ] My addition is ordered alphabetically
-   [ ] My submission has a useful description
-   [x] The description does not have more than 100 characters
-   [x] The description does not end with punctuation
-   [x] Each table column is padded with one space on either side
-   [x] I have searched the repository for any relevant issues or pull requests
-   [ ] Any category I am creating has the minimum requirement of 3 items
-   [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by JuanPabloDiaz** [comment]
image

**Comment by JuanPabloDiaz** [comment]
I found a [simpler workflow](https://github.com/emmabostian/developer-portfolios/blob/master/.github/workflows/link-checker.yml) that you could use instead. I test it in one of my projects and it does the job. 

You might need to change the argument to check all markdown files and you are good to go.

**Comment by marcelscruz** [comment]
I'm merging the one you created to see how it works, then if needed I'll update the workflow.
Thank you so much, Juan!

**Comment by JuanPabloDiaz** [comment]
> I'm merging the one you created to see how it works, then if needed I'll update the workflow. Thank you so much, Juan!

You're welcome @marcelscruz

**Pull request merged**
