### PR TITLE
BigBookApi + API League

### PR DESCRIPTION
**Pull request by ddsky**
-   [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/marcelscruz/public-apis/blob/main/CONTRIBUTING.md)
-   [x] My addition is ordered alphabetically
-   [x] My submission has a useful description
-   [x] The description does not have more than 100 characters
-   [x] The description does not end with punctuation
-   [x] Each table column is padded with one space on either side
-   [x] I have searched the repository for any relevant issues or pull requests
-   [x] Any category I am creating has the minimum requirement of 3 items
-   [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by ddsky** [comment]
added bigbookapi.com and apileague.com

**Comment by marcelscruz** [comment]
Could you please make sure the README file isn't formatted with your rules, because this adds a lot of diffs.
Also, only the README file should be changed.
Thank you.

**Comment by ddsky** [comment]
> Could you please make sure the README file isn't formatted with your rules, because this adds a lot of diffs. Also, only the README file should be changed. Thank you.

Hi @marcelscruz which formatting is not correct? I have not applied any rules other than copying format from existing entries.

**Comment by marcelscruz** [comment]
[Check this diff here](https://github.com/marcelscruz/public-apis/pull/318/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), you'll see most of the file is re-formatted.
If you have Prettier, I suggest disabling for this codebase.

**Review by Mjdesignco — APPROVED** [review]

**Pull request closed without merging**
