### PR TITLE
Add Safe Text & Word to word APIs to Text analysis

### PR DESCRIPTION
**Pull request by bacloud22**
-   [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/marcelscruz/public-apis/blob/main/CONTRIBUTING.md)
-   [x] My addition is ordered alphabetically
-   [x] My submission has a useful description
-   [x] The description does not have more than 100 characters
-   [x] The description does not end with punctuation
-   [x] Each table column is padded with one space on either side
-   [x] I have searched the repository for any relevant issues or pull requests
-   [x] Any category I am creating has the minimum requirement of 3 items
-   [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by bacloud23** [comment]
Hi @marcelscruz 
Can you please verify this ? 
thank you

**Comment by JuanPabloDiaz** [comment]
Hi @bacloud23,

Thank you for your contribution to the project! I am currently encountering a "Page not found" error when trying to access the [Word to word translator](https://rapidapi.com/bacloud14/api/translator203).

Would you be able to double-check the link or provide any updates on the API's availability? Once this is resolved, we'd be happy to merge your contribution.

best,
Juan Diaz

**Comment by bacloud23** [comment]
Hi @JuanPabloDiaz 
Thank you for checking!
 You are right it is cancelled and I no longer want to put it. 
Please edit or give me some time to reedit the pull request. 

Safe-Text API will always be up. 
Kindly

**Comment by bacloud22** [comment]
Hi @JuanPabloDiaz I've made the proper changer.
Thank you.

**Pull request merged**
